# -*- coding: utf-8 -*-
"""trignometrycalculator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n0YR5mjze3pzzJFPt4f4AJRm8DGscl6W
"""

# welome to my trignometry calculator 
import math 
print('do it like sin,40')
number=input("please enter your number")
split_num=number.split(',')
value=int(split_num[1])

#the trignometry part 
if split_num[0]=='sin':
  print(math.sin(value))

elif split_num[0]=='cos':
  print(math.cos(value))

elif split_num[0]=='tan':
  print(math.tan(value))

else:
  print("function not found.please try again later")